"""Skill-augmented agent that integrates skill retrieval with MempAgent."""

import copy
import logging
from typing import Any, Dict, List, Optional, Union

from qskill.agent.memp_agent import MempAgent
from qskill.skills.skill import Skill
from qskill.skills.integration import SkillIntegrator

logger = logging.getLogger(__name__)


class SkillAgent:
    """Agent that augments MempAgent with skill layer capabilities.

    This agent retrieves relevant skills based on the current observation
    and task description, then injects them into the agent's context
    before each action generation.
    """

    def __init__(
        self,
        agent: MempAgent,
        skill_integrator: Optional[SkillIntegrator] = None,
    ):
        """Initialize the SkillAgent.

        Args:
            agent: The base MempAgent to wrap.
            skill_integrator: Optional SkillIntegrator for skill retrieval.
                If None, skills are not used.
        """
        self.agent = agent
        self.skill_integrator = skill_integrator
        self.llm = agent.llm

    def retrieve_skills(
        self,
        task_description: str,
        task_type: str,
        observation: Optional[str] = None,
        k: Optional[int] = None,
    ) -> List[Skill]:
        """Retrieve relevant skills for the current context.

        Args:
            task_description: Description of the current task.
            task_type: Type/category of the task.
            observation: Current observation (for dynamic retrieval).
            k: Number of skills to retrieve.

        Returns:
            List of relevant Skill objects.
        """
        if not self.skill_integrator:
            return []
        return self.skill_integrator.retrieve_skills(
            task_description=task_description,
            task_type=task_type,
            observation=observation,
            k=k,
        )

    def _inject_skills_into_messages(
        self,
        messages: List[Dict[str, str]],
        skills: List[Skill],
    ) -> List[Dict[str, str]]:
        """Inject skills into messages as a system addition.

        Args:
            messages: Current message list.
            skills: Skills to inject.

        Returns:
            Messages with skills injected.
        """
        if not skills or not self.skill_integrator:
            return messages

        # Find the system message and insert skills after it
        skills_text = self.skill_integrator.format_skills_for_context(skills)
        if not skills_text:
            return messages

        # Create skill context message
        skill_message = {
            "role": "system",
            "content": f"\n{skills_text}"
        }

        # Insert after first system message
        inserted = False
        for i, msg in enumerate(messages):
            if msg.get("role") == "system":
                messages.insert(i + 1, skill_message)
                inserted = True
                break

        if not inserted:
            messages.insert(0, skill_message)

        return messages

    def act(
        self,
        observation: str,
        history_messages: List[Dict[str, str]],
        task_description: str,
        task_type: str,
        first_step: bool = False,
    ) -> Optional[str]:
        """Generate next action with skill-augmented context.

        Args:
            observation: Current environment observation.
            history_messages: Conversation history.
            task_description: Task description for skill retrieval.
            task_type: Task type for skill retrieval.
            first_step: Whether this is the first step.

        Returns:
            Action string generated by the LLM, or None if generation fails.
        """
        # Retrieve relevant skills based on current context
        skills = self.retrieve_skills(
            task_description=task_description,
            task_type=task_type,
            observation=observation,
        )

        # Clone messages and inject skills
        current_messages = copy.deepcopy(history_messages)
        current_messages = self._inject_skills_into_messages(current_messages, skills)

        # If first step, construct initial messages instead
        if first_step and not history_messages:
            current_messages = self.agent._construct_messages(
                task_description=task_description,
                retrieved_memories=[],  # Empty list for initial construction
                task_type=task_type
            )
            current_messages = self._inject_skills_into_messages(current_messages, skills)

        # Call the underlying agent
        return self.agent.act(
            observation=observation,
            history_messages=current_messages,
            first_step=first_step,
        )

    def _construct_messages(
        self,
        task_description: str,
        retrieved_memories: Any,
        task_type: str
    ) -> List[Dict[str, str]]:
        """Proxy to underlying agent's message construction."""
        return self.agent._construct_messages(
            task_description=task_description,
            retrieved_memories=retrieved_memories,
            task_type=task_type
        )
